# Generated by Django 4.1.1 on 2022-09-25 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internshipApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='title',
        ),
    ]
